# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
