# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('about', models.CharField(blank=True, max_length=100)),
                ('photo', models.URLField(blank=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('karma', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseproject.Language')),
                ('theme', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseproject.Theme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
